[user]
default=tromanow

[boot]
systemd=true
command=systemctl start user@1000.service

[automount]
enabled = false

[interop]
enabled = false
appendWindowsPath = false

[network]
hostname = wsl-dev
generateHosts = false

